persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Standard TCP listener for internal services and physical devices
listener 1883 0.0.0.0
allow_anonymous true

# WebSockets listener for frontend and future mobile apps (reverse-proxied via Nginx)
listener 9001 0.0.0.0
protocol websockets
allow_anonymous true
